{% set name = "ecos" %}
{% set version = "2.0.14" %}
{% set sha256 = "64b3201c0e0a7f0129050557c4ac50b00031e80a10534506dba1200c8dc1efe4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --no-build-isolation --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.6,<3
    - scipy >=0.9

test:
  requires:
    - pip
    - numpy {{ numpy }}
    - pytest
  imports:
    - ecos
    - _ecos
  files:
    - test_interface_bb.py  # copied from repo; isn't in the sdist
    - test_interface.py # copied from repo; isn't in the sdist
  commands:
    - python test_interface_bb.py
    - python test_interface.py
    - pip check

about:
  home: https://github.com/embotech/ecos/wiki
  description: 'This is the Python package for ECOS: Embedded Cone Solver. See Github page for more information.'
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # in recipe for now; https://github.com/embotech/ecos-python/pull/15
  summary: 'Python interface for ECOS a lightweight conic solver for second-order cone programming'
  dev_url: https://github.com/embotech/ecos-python
  doc_url: https://github.com/embotech/ecos-python

extra:
  recipe-maintainers:
    - dougalsutherland
    - h-vetinari
