# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "odPJycR6gq5EbmDsm+8ueueeUFc4fWLQL6+9kcFQG6a6KKWtkmsqmbcA2wxFIminOsu6vSbh4drhI8KdO821Je9/GaPKvmx/VGRLSs0fQMRdDyj9bh5KI+G892fS905mLsWAwCzTHALG6e+CTe0LZNnEeIWhIwBEs9Gczb9iBU5ylvG4xa/SpgPg9ByahW35AxsSIq9mpZvvIxu3utQkGJCEKW+6vbvCDvit8TVuhIOUQAvvcOaCHBsJ/QB2OxnmXPqX9OBaQNATHEoW9p4znZlB6pm2gvLviI2n6bxmiXLzeH40YWE9JkwAPgCQtRCJwKdJSzzhZLXmYKW1FQjxpyaz0uzX+dIyr5HJxa4ZtVl1xDpnvkaXRvoEIZMGVKPKwiDIe3I2Pg3uhGvQvEtqsuD4dhrnHMK/r+7oue/LbGgkyB/WInQuExjh+rfTcDq+Y9jMTnUkdxzSx3dtSD5MssKTiTLJegpzlGBvLE9AJtNtEmGCeEedf9svA5bFyFYjF1DdRfrfhfVU9M2QDUMnZR/IQdtWE8OJG+dCOWnF0jAjyaz2uvDofJfTgK6XhpZ40D2HFVwuPOE6poUoXXIbfHHfSbINTA3R7V4t+YDUS4HySwyTT1bAG2UwujcQZSB6X5AMph946h5mIt97TcQ+IgJwsDS0WQg7bVBy9LfmYeA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
