travis:
  secure:
    BINSTAR_TOKEN: ATZpVlEYD7fJXflv22ArpesohnqcgY9yaHM9nWiUj4PpqkekH2K3IuUm+zW2MsHfkDU6GSrMo2D/nQs5SdUgE2uCUY0DHQrilq2uDHiUOUSbSn03WNPW5giCcfQOAx5ULyojvSGHl+8yXNuq5o7l2I6uGs2JCtsq/dl9bI18yJlqpoTqgggQ+dfIBIcF9WbZDYuwiLzQrnzfoQO0ydYTg/bSjFvw0EtGn6lR3ay5X8Spl40N4CsjV3oseDr24AYur8R4cNhqJ0IljozLK4JvPFIJcMY98mFbd6IevjjkQO4ogjIm2yKuMSolSV2l1dznPGMzzWQ9L97qpEYHXmkxR6wDfZJ7Qa7NkdJn6dGaxE9HmXIU2y3spZa+ZHbrRsC8DkkS+db67mDKbE5C0kMFvVYCyGrCmNfQK+ezOGycCMgFv1cO6jQvaPhT2G8/tEJsUbHUmnd/NBtIdlv8rHoJN3wPoMnBzipx22OCqD3mOaVJVVLjXq6s9spwakexTPc9I46Wb2TPQJzN+aMSV/zto0iOYGDTaSv9X0U/VFHcOusmtqAcfqAVQC9su0MgJqXlI+c58gUZxCqFHrqAU3i438zIryZaOG4h3UIVfeO6KvOqay0wn4kya4zTg5vN4yYZXxdWFcFpBonalZz7htNmTQ3hApQhX3WLGU7gemYAyS8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
